# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cameraLocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cameraLocation
  pod ‘QRCodeReader.swift'

  target 'cameraLocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cameraLocationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
